# Proyecto del Día 8 - Análisis de Datos Meteorológicos

Este proyecto consiste en analizar un conjunto de datos meteorológicos utilizando Python y NumPy. 
El objetivo es aplicar las técnicas de manipulación de arrays, tratamiento de datos faltantes, 
y análisis estadístico básico en un conjunto de datos del mundo real.

## Tareas a Realizar:
1. Crear un DataFrame a partir de los datos del archivo **datos_meteorologicos.csv** provisto en esta lección.
2. Realizar observaciones iniciales de los datos con Pandas.
3. Convertir las columnas del DataFrame en arrays de NumPy.
4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.
5. Realizar análisis estadísticos básicos. Mínimamente se espera que puedas extraer la siguiente información de tus arrays:
    * La temperatura promedio
    * El total de precipitaciones
    * La máxima humedad registrada
    * La fecha más calurosa
    * La fehca más fría
6. Exportar los resultados a un nuevo archivo CSV.

¡Mucha suerte con tu proyecto!


In [2]:
import pandas as pd
import numpy as np

### 1. Crear un DataFrame a partir de los datos del archivo datos_meteorologicos.csv provisto en esta lección.

In [4]:
df = pd.read_csv(r"C:\Users\nico\Desktop\BD\datos_meteorologicos.csv")
df

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

### 2. Realizar observaciones iniciales de los datos con Pandas.

In [6]:
df.shape

(5110, 4)

In [7]:
df.head()

Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637
1  02/01/2010    25.759468       5.315628  30.633530
2  03/01/2010    20.138169      15.317706  41.496715
3  04/01/2010    17.244159      13.151008  90.684704
4  05/01/2010    11.182740      16.413667  22.116422

In [8]:
df.tail()

Fecha  Temperatura  Precipitación    Humedad
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


In [10]:
df.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

In [11]:
df.drop_duplicates()

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

### 3. Convertir las columnas del DataFrame en arrays de NumPy.

In [13]:
mi_array_temperatura =df['Temperatura'].to_numpy()
mi_array_temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

In [14]:
mi_array_humedad = df['Humedad'].to_numpy()
mi_array_humedad

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
               nan, 50.64621058])

In [15]:
mi_array_precipitacion = df['Precipitación'].to_numpy()
mi_array_precipitacion

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
               nan,  7.33051023])

### 4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.

In [17]:
promedio_temperatura = np.nanmean(mi_array_temperatura)
mi_array_temperatura = np.where(np.isnan(mi_array_temperatura),promedio_temperatura,mi_array_temperatura)
mi_array_temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
       14.88929572, 37.30804318])

In [18]:
promedio_precipitacion = np.nanmean(mi_array_precipitacion)
mi_array_precipitacion = np.where(np.isnan(mi_array_precipitacion),promedio_precipitacion,mi_array_precipitacion)
mi_array_precipitacion

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
        9.9016036 ,  7.33051023])

In [19]:
promedio_humedad = np.nanmean(mi_array_humedad)
mi_array_humedad = np.where(np.isnan(mi_array_humedad),promedio_humedad,mi_array_humedad)
mi_array_humedad

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
       54.3590608 , 50.64621058])

### 5. Realizar análisis estadísticos básicos.

##### Temperatura promedio

In [21]:
temperatura_promedio = np.nanmean(mi_array_temperatura)
temperatura_promedio

14.889295723531713

##### Total de precipitaciones

In [23]:
total_precipitaciones = np.nansum(mi_array_precipitacion)
total_precipitaciones

50597.19438939993

##### Máxima humedad registrada

In [25]:
maxima_humedad = np.nanmax(mi_array_humedad)
maxima_humedad

99.99658156071747

##### Fecha más calurosa

In [79]:
temperatura_maxima = np.where(mi_array_temperatura == np.max(mi_array_temperatura))[0][0]
temp_max= df['Fecha'].iloc[temperatura_maxima]

##### Fehca más fría

In [77]:
temperatura_minima = np.where(mi_array_temperatura == np.min(mi_array_temperatura))[0][0]
temp_min = df['Fecha'].iloc[temperatura_minima]
temp_min

'23/07/2020'

### 6. Exportar los resultados a un nuevo archivo CSV.

In [81]:
resultados = pd.DataFrame({
    'Metrica': ['Temperatura Promedio', 'Total Precipitaciones', 'Máxima Humedad', 'Fecha más calurosa', 'Fecha más fría'],
    'Valores' : [temperatura_promedio,total_precipitaciones,maxima_humedad,temp_max,temp_min]
})
resultados

Metrica       Valores
0   Temperatura Promedio     14.889296
1  Total Precipitaciones  50597.194389
2         Máxima Humedad     99.996582
3     Fecha más calurosa    12/07/2017
4         Fecha más fría    23/07/2020

In [85]:
resultados.to_csv(r'C:\Users\nico\Desktop\BD\resultados2.csv', index = False)